# Generated by Django 5.1.1 on 2024-09-09 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BakeryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receive_time', models.DateTimeField()),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_phone_number', models.CharField(max_length=20)),
                ('is_received', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='BakeryItemAllergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pan_de_reserve.allergy')),
                ('bakery_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pan_de_reserve.bakeryitem')),
            ],
        ),
        migrations.CreateModel(
            name='ReservationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bakery_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pan_de_reserve.bakeryitem')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pan_de_reserve.reservation')),
            ],
        ),
    ]
